Bad Requests: Block junk requests which set a tag url, with a stringy 'tag_slug__and' value, which expects an array.
These requests are junk/spam/pentester and not user queries.

Avoids hitting a PHP fatal:
> E_ERROR: Uncaught Error: [] operator not supported for strings in wp-includes/class-wp-query.php:1334

See https://core.trac.wordpress.org/ticket/60745


git-svn-id: https://meta.svn.wordpress.org/sites/trunk@14661 74240141-8908-4e6f-9713-ba540dce6ec7